
// This file is simplified to only contain data necessary for the map to function.
// The SVG 'path' properties have been removed as they are no longer needed
// by the new `react-simple-maps` component, which uses GeoJSON.

export type Country = {
  name: string;
  iso2: string;
  aliases: string[];
  continent: 'Europe' | 'Asia & Oceania' | 'The Americas' | 'Africa' | 'Antarctica';
  guessed?: boolean;
};

export const countries: Country[] = [
  // Europe
  { name: 'Albania', iso2: 'AL', aliases: [], continent: 'Europe' },
  { name: 'Andorra', iso2: 'AD', aliases: [], continent: 'Europe' },
  { name: 'Austria', iso2: 'AT', aliases: [], continent: 'Europe' },
  { name: 'Belarus', iso2: 'BY', aliases: [], continent: 'Europe' },
  { name: 'Belgium', iso2: 'BE', aliases: [], continent: 'Europe' },
  { name: 'Bosnia and Herzegovina', iso2: 'BA', aliases: [], continent: 'Europe' },
  { name: 'Bulgaria', iso2: 'BG', aliases: [], continent: 'Europe' },
  { name: 'Croatia', iso2: 'HR', aliases: [], continent: 'Europe' },
  { name: 'Cyprus', iso2: 'CY', aliases: [], continent: 'Europe' },
  { name: 'Czech Republic', iso2: 'CZ', aliases: ['Czechia'], continent: 'Europe' },
  { name: 'Denmark', iso2: 'DK', aliases: [], continent: 'Europe' },
  { name: 'Estonia', iso2: 'EE', aliases: [], continent: 'Europe' },
  { name: 'Finland', iso2: 'FI', aliases: [], continent: 'Europe' },
  { name: 'France', iso2: 'FR', aliases: [], continent: 'Europe' },
  { name: 'Germany', iso2: 'DE', aliases: [], continent: 'Europe' },
  { name: 'Greece', iso2: 'GR', aliases: [], continent: 'Europe' },
  { name: 'Hungary', iso2: 'HU', aliases: [], continent: 'Europe' },
  { name: 'Iceland', iso2: 'IS', aliases: [], continent: 'Europe' },
  { name: 'Ireland', iso2: 'IE', aliases: [], continent: 'Europe' },
  { name: 'Italy', iso2: 'IT', aliases: [], continent: 'Europe' },
  { name: 'Kosovo', iso2: 'XK', aliases: [], continent: 'Europe' },
  { name: 'Latvia', iso2: 'LV', aliases: [], continent: 'Europe' },
  { name: 'Liechtenstein', iso2: 'LI', aliases: [], continent: 'Europe' },
  { name: 'Lithuania', iso2: 'LT', aliases: [], continent: 'Europe' },
  { name: 'Luxembourg', iso2: 'LU', aliases: [], continent: 'Europe' },
  { name: 'Malta', iso2: 'MT', aliases: [], continent: 'Europe' },
  { name: 'Moldova', iso2: 'MD', aliases: [], continent: 'Europe' },
  { name: 'Monaco', iso2: 'MC', aliases: [], continent: 'Europe' },
  { name: 'Montenegro', iso2: 'ME', aliases: [], continent: 'Europe' },
  { name: 'Netherlands', iso2: 'NL', aliases: ['Holland'], continent: 'Europe' },
  { name: 'North Macedonia', iso2: 'MK', aliases: [], continent: 'Europe' },
  { name: 'Norway', iso2: 'NO', aliases: [], continent: 'Europe' },
  { name: 'Poland', iso2: 'PL', aliases: [], continent: 'Europe' },
  { name: 'Portugal', iso2: 'PT', aliases: [], continent: 'Europe' },
  { name: 'Romania', iso2: 'RO', aliases: [], continent: 'Europe' },
  { name: 'Russia', iso2: 'RU', aliases: [], continent: 'Europe' },
  { name: 'San Marino', iso2: 'SM', aliases: [], continent: 'Europe' },
  { name: 'Serbia', iso2: 'RS', aliases: [], continent: 'Europe' },
  { name: 'Slovakia', iso2: 'SK', aliases: [], continent: 'Europe' },
  { name: 'Slovenia', iso2: 'SI', aliases: [], continent: 'Europe' },
  { name: 'Spain', iso2: 'ES', aliases: [], continent: 'Europe' },
  { name: 'Sweden', iso2: 'SE', aliases: [], continent: 'Europe' },
  { name: 'Switzerland', iso2: 'CH', aliases: [], continent: 'Europe' },
  { name: 'Ukraine', iso2: 'UA', aliases: [], continent: 'Europe' },
  { name: 'United Kingdom', iso2: 'GB', aliases: ['UK', 'Great Britain', 'Britain'], continent: 'Europe' },
  { name: 'Vatican City', iso2: 'VA', aliases: [], continent: 'Europe' },

  // Asia & Oceania
  { name: 'Afghanistan', iso2: 'AF', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Armenia', iso2: 'AM', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Azerbaijan', iso2: 'AZ', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Bahrain', iso2: 'BH', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Bangladesh', iso2: 'BD', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Bhutan', iso2: 'BT', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Brunei', iso2: 'BN', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Cambodia', iso2: 'KH', aliases: [], continent: 'Asia & Oceania' },
  { name: 'China', iso2: 'CN', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Georgia', iso2: 'GE', aliases: [], continent: 'Asia & Oceania' },
  { name: 'India', iso2: 'IN', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Indonesia', iso2: 'ID', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Iran', iso2: 'IR', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Iraq', iso2: 'IQ', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Israel', iso2: 'IL', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Japan', iso2: 'JP', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Jordan', iso2: 'JO', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Kazakhstan', iso2: 'KZ', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Kuwait', iso2: 'KW', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Kyrgyzstan', iso2: 'KG', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Laos', iso2: 'LA', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Lebanon', iso2: 'LB', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Malaysia', iso2: 'MY', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Maldives', iso2: 'MV', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Mongolia', iso2: 'MN', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Myanmar', iso2: 'MM', aliases: ['Burma'], continent: 'Asia & Oceania' },
  { name: 'Nepal', iso2: 'NP', aliases: [], continent: 'Asia & Oceania' },
  { name: 'North Korea', iso2: 'KP', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Oman', iso2: 'OM', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Pakistan', iso2: 'PK', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Palestine', iso2: 'PS', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Philippines', iso2: 'PH', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Qatar', iso2: 'QA', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Saudi Arabia', iso2: 'SA', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Singapore', iso2: 'SG', aliases: [], continent: 'Asia & Oceania' },
  { name: 'South Korea', iso2: 'KR', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Sri Lanka', iso2: 'LK', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Syria', iso2: 'SY', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Taiwan', iso2: 'TW', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Tajikistan', iso2: 'TJ', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Thailand', iso2: 'TH', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Timor-Leste', iso2: 'TL', aliases: ['East Timor'], continent: 'Asia & Oceania' },
  { name: 'Turkey', iso2: 'TR', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Turkmenistan', iso2: 'TM', aliases: [], continent: 'Asia & Oceania' },
  { name: 'United Arab Emirates', iso2: 'AE', aliases: ['UAE'], continent: 'Asia & Oceania' },
  { name: 'Uzbekistan', iso2: 'UZ', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Vietnam', iso2: 'VN', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Yemen', iso2: 'YE', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Australia', iso2: 'AU', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Fiji', iso2: 'FJ', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Kiribati', iso2: 'KI', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Marshall Islands', iso2: 'MH', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Micronesia', iso2: 'FM', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Nauru', iso2: 'NR', aliases: [], continent: 'Asia & Oceania' },
  { name: 'New Zealand', iso2: 'NZ', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Palau', iso2: 'PW', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Papua New Guinea', iso2: 'PG', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Samoa', iso2: 'WS', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Solomon Islands', iso2: 'SB', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Tonga', iso2: 'TO', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Tuvalu', iso2: 'TV', aliases: [], continent: 'Asia & Oceania' },
  { name: 'Vanuatu', iso2: 'VU', aliases: [], continent: 'Asia & Oceania' },

  // Africa
  { name: 'Algeria', iso2: 'DZ', aliases: [], continent: 'Africa' },
  { name: 'Angola', iso2: 'AO', aliases: [], continent: 'Africa' },
  { name: 'Benin', iso2: 'BJ', aliases: [], continent: 'Africa' },
  { name: 'Botswana', iso2: 'BW', aliases: [], continent: 'Africa' },
  { name: 'Burkina Faso', iso2: 'BF', aliases: [], continent: 'Africa' },
  { name: 'Burundi', iso2: 'BI', aliases: [], continent: 'Africa' },
  { name: 'Cabo Verde', iso2: 'CV', aliases: ['Cape Verde'], continent: 'Africa' },
  { name: 'Cameroon', iso2: 'CM', aliases: [], continent: 'Africa' },
  { name: 'Central African Republic', iso2: 'CF', aliases: [], continent: 'Africa' },
  { name: 'Chad', iso2: 'TD', aliases: [], continent: 'Africa' },
  { name: 'Comoros', iso2: 'KM', aliases: [], continent: 'Africa' },
  { name: 'Congo', iso2: 'CG', aliases: ['Republic of the Congo'], continent: 'Africa' },
  { name: 'DR Congo', iso2: 'CD', aliases: ['Democratic Republic of the Congo'], continent: 'Africa' },
  { name: 'Djibouti', iso2: 'DJ', aliases: [], continent: 'Africa' },
  { name: 'Egypt', iso2: 'EG', aliases: [], continent: 'Africa' },
  { name: 'Equatorial Guinea', iso2: 'GQ', aliases: [], continent: 'Africa' },
  { name: 'Eritrea', iso2: 'ER', aliases: [], continent: 'Africa' },
  { name: 'Eswatini', iso2: 'SZ', aliases: ['Swaziland'], continent: 'Africa' },
  { name: 'Ethiopia', iso2: 'ET', aliases: [], continent: 'Africa' },
  { name: 'Gabon', iso2: 'GA', aliases: [], continent: 'Africa' },
  { name: 'Gambia', iso2: 'GM', aliases: [], continent: 'Africa' },
  { name: 'Ghana', iso2: 'GH', aliases: [], continent: 'Africa' },
  { name: 'Guinea', iso2: 'GN', aliases: [], continent: 'Africa' },
  { name: 'Guinea-Bissau', iso2: 'GW', aliases: [], continent: 'Africa' },
  { name: 'Ivory Coast', iso2: 'CI', aliases: ["Côte d'Ivoire"], continent: 'Africa' },
  { name: 'Kenya', iso2: 'KE', aliases: [], continent: 'Africa' },
  { name: 'Lesotho', iso2: 'LS', aliases: [], continent: 'Africa' },
  { name: 'Liberia', iso2: 'LR', aliases: [], continent: 'Africa' },
  { name: 'Libya', iso2: 'LY', aliases: [], continent: 'Africa' },
  { name: 'Madagascar', iso2: 'MG', aliases: [], continent: 'Africa' },
  { name: 'Malawi', iso2: 'MW', aliases: [], continent: 'Africa' },
  { name: 'Mali', iso2: 'ML', aliases: [], continent: 'Africa' },
  { name: 'Mauritania', iso2: 'MR', aliases: [], continent: 'Africa' },
  { name: 'Mauritius', iso2: 'MU', aliases: [], continent: 'Africa' },
  { name: 'Morocco', iso2: 'MA', aliases: [], continent: 'Africa' },
  { name: 'Mozambique', iso2: 'MZ', aliases: [], continent: 'Africa' },
  { name: 'Namibia', iso2: 'NA', aliases: [], continent: 'Africa' },
  { name: 'Niger', iso2: 'NE', aliases: [], continent: 'Africa' },
  { name: 'Nigeria', iso2: 'NG', aliases: [], continent: 'Africa' },
  { name: 'Rwanda', iso2: 'RW', aliases: [], continent: 'Africa' },
  { name: 'Sao Tome and Principe', iso2: 'ST', aliases: [], continent: 'Africa' },
  { name: 'Senegal', iso2: 'SN', aliases: [], continent: 'Africa' },
  { name: 'Seychelles', iso2: 'SC', aliases: [], continent: 'Africa' },
  { name: 'Sierra Leone', iso2: 'SL', aliases: [], continent: 'Africa' },
  { name: 'Somalia', iso2: 'SO', aliases: [], continent: 'Africa' },
  { name: 'South Africa', iso2: 'ZA', aliases: [], continent: 'Africa' },
  { name: 'South Sudan', iso2: 'SS', aliases: [], continent: 'Africa' },
  { name: 'Sudan', iso2: 'SD', aliases: [], continent: 'Africa' },
  { name: 'Tanzania', iso2: 'TZ', aliases: [], continent: 'Africa' },
  { name: 'Togo', iso2: 'TG', aliases: [], continent: 'Africa' },
  { name: 'Tunisia', iso2: 'TN', aliases: [], continent: 'Africa' },
  { name: 'Uganda', iso2: 'UG', aliases: [], continent: 'Africa' },
  { name: 'Zambia', iso2: 'ZM', aliases: [], continent: 'Africa' },
  { name: 'Zimbabwe', iso2: 'ZW', aliases: [], continent: 'Africa' },
  
  // The Americas
  { name: 'Antigua and Barbuda', iso2: 'AG', aliases: [], continent: 'The Americas' },
  { name: 'Bahamas', iso2: 'BS', aliases: [], continent: 'The Americas' },
  { name: 'Barbados', iso2: 'BB', aliases: [], continent: 'The Americas' },
  { name: 'Belize', iso2: 'BZ', aliases: [], continent: 'The Americas' },
  { name: 'Canada', iso2: 'CA', aliases: [], continent: 'The Americas' },
  { name: 'Costa Rica', iso2: 'CR', aliases: [], continent: 'The Americas' },
  { name: 'Cuba', iso2: 'CU', aliases: [], continent: 'The Americas' },
  { name: 'Dominica', iso2: 'DM', aliases: [], continent: 'The Americas' },
  { name: 'Dominican Republic', iso2: 'DO', aliases: [], continent: 'The Americas' },
  { name: 'El Salvador', iso2: 'SV', aliases: [], continent: 'The Americas' },
  { name: 'Grenada', iso2: 'GD', aliases: [], continent: 'The Americas' },
  { name: 'Guatemala', iso2: 'GT', aliases: [], continent: 'The Americas' },
  { name: 'Haiti', iso2: 'HT', aliases: [], continent: 'The Americas' },
  { name: 'Honduras', iso2: 'HN', aliases: [], continent: 'The Americas' },
  { name: 'Jamaica', iso2: 'JM', aliases: [], continent: 'The Americas' },
  { name: 'Mexico', iso2: 'MX', aliases: [], continent: 'The Americas' },
  { name: 'Nicaragua', iso2: 'NI', aliases: [], continent: 'The Americas' },
  { name: 'Panama', iso2: 'PA', aliases: [], continent: 'The Americas' },
  { name: 'Saint Kitts and Nevis', iso2: 'KN', aliases: [], continent: 'The Americas' },
  { name: 'Saint Lucia', iso2: 'LC', aliases: [], continent: 'The Americas' },
  { name: 'Saint Vincent and the Grenadines', iso2: 'VC', aliases: [], continent: 'The Americas' },
  { name: 'Trinidad and Tobago', iso2: 'TT', aliases: [], continent: 'The Americas' },
  { name: 'United States', iso2: 'US', aliases: ['USA', 'America'], continent: 'The Americas' },
  { name: 'Argentina', iso2: 'AR', aliases: [], continent: 'The Americas' },
  { name: 'Bolivia', iso2: 'BO', aliases: [], continent: 'The Americas' },
  { name: 'Brazil', iso2: 'BR', aliases: [], continent: 'The Americas' },
  { name: 'Chile', iso2: 'CL', aliases: [], continent: 'The Americas' },
  { name: 'Colombia', iso2: 'CO', aliases: [], continent: 'The Americas' },
  { name: 'Ecuador', iso2: 'EC', aliases: [], continent: 'The Americas' },
  { name: 'Guyana', iso2: 'GY', aliases: [], continent: 'The Americas' },
  { name: 'Paraguay', iso2: 'PY', aliases: [], continent: 'The Americas' },
  { name: 'Peru', iso2: 'PE', aliases: [], continent: 'The Americas' },
  { name: 'Suriname', iso2: 'SR', aliases: [], continent: 'The Americas' },
  { name: 'Uruguay', iso2: 'UY', aliases: [], continent: 'The Americas' },
  { name: 'Venezuela', iso2: 'VE', aliases: [], continent: 'The Americas' },
  
  // Antarctica
  { name: 'Antarctica', iso2: 'AQ', aliases: [], continent: 'Antarctica' },
];
