// This file is simplified to only contain data necessary for the map to function.
// The SVG 'path' properties have been removed as they are no longer needed
// by the new `react-simple-maps` component, which uses GeoJSON.

export type Country = {
  name: string;
  iso2: string;
  aliases: string[];
  continent: 'Europe' | 'Asia' | 'Africa' | 'North America' | 'South America' | 'Oceania' | 'Antarctica';
};

export const countries: Country[] = [
  // Europe
  { name: 'France', iso2: 'FR', aliases: [], continent: 'Europe' },
  { name: 'Germany', iso2: 'DE', aliases: [], continent: 'Europe' },
  { name: 'Spain', iso2: 'ES', aliases: [], continent: 'Europe' },
  { name: 'Italy', iso2: 'IT', aliases: [], continent: 'Europe' },
  { name: 'United Kingdom', iso2: 'GB', aliases: ['UK', 'Great Britain', 'Britain'], continent: 'Europe' },
  { name: 'Portugal', iso2: 'PT', aliases: [], continent: 'Europe' },
  { name: 'Poland', iso2: 'PL', aliases: [], continent: 'Europe' },
  { name: 'Sweden', iso2: 'SE', aliases: [], continent: 'Europe' },
  { name: 'Norway', iso2: 'NO', aliases: [], continent: 'Europe' },
  { name: 'Finland', iso2: 'FI', aliases: [], continent: 'Europe' },
  { name: 'Greece', iso2: 'GR', aliases: [], continent: 'Europe' },
  { name: 'Ukraine', iso2: 'UA', aliases: [], continent: 'Europe' },
  { name: 'Romania', iso2: 'RO', aliases: [], continent: 'Europe' },
  { name: 'Netherlands', iso2: 'NL', aliases: ['Holland'], continent: 'Europe' },
  { name: 'Belgium', iso2: 'BE', aliases: [], continent: 'Europe' },
  { name: 'Switzerland', iso2: 'CH', aliases: [], continent: 'Europe' },
  { name: 'Austria', iso2: 'AT', aliases: [], continent: 'Europe' },
  { name: 'Ireland', iso2: 'IE', aliases: [], continent: 'Europe' },
  { name: 'Czech Republic', iso2: 'CZ', aliases: ['Czechia'], continent: 'Europe' },
  { name: 'Hungary', iso2: 'HU', aliases: [], continent: 'Europe' },
  { name: 'Denmark', iso2: 'DK', aliases: [], continent: 'Europe' },
  { name: 'Iceland', iso2: 'IS', aliases: [], continent: 'Europe' },
  { name: 'Slovakia', iso2: 'SK', aliases: [], continent: 'Europe' },
  { name: 'Croatia', iso2: 'HR', aliases: [], continent: 'Europe' },
  { name: 'Slovenia', iso2: 'SI', aliases: [], continent: 'Europe' },
  { name: 'Serbia', iso2: 'RS', aliases: [], continent: 'Europe' },
  { name: 'Bosnia and Herzegovina', iso2: 'BA', aliases: [], continent: 'Europe' },
  { name: 'Montenegro', iso2: 'ME', aliases: [], continent: 'Europe' },
  { name: 'North Macedonia', iso2: 'MK', aliases: [], continent: 'Europe' },
  { name: 'Albania', iso2: 'AL', aliases: [], continent: 'Europe' },
  { name: 'Bulgaria', iso2: 'BG', aliases: [], continent: 'Europe' },
  { name: 'Estonia', iso2: 'EE', aliases: [], continent: 'Europe' },
  { name: 'Latvia', iso2: 'LV', aliases: [], continent: 'Europe' },
  { name: 'Lithuania', iso2: 'LT', aliases: [], continent: 'Europe' },
  { name: 'Belarus', iso2: 'BY', aliases: [], continent: 'Europe' },
  { name: 'Moldova', iso2: 'MD', aliases: [], continent: 'Europe' },
  { name: 'Andorra', iso2: 'AD', aliases: [], continent: 'Europe' },
  { name: 'Monaco', iso2: 'MC', aliases: [], continent: 'Europe' },
  { name: 'San Marino', iso2: 'SM', aliases: [], continent: 'Europe' },
  { name: 'Vatican City', iso2: 'VA', aliases: [], continent: 'Europe' },
  { name: 'Liechtenstein', iso2: 'LI', aliases: [], continent: 'Europe' },
  { name: 'Luxembourg', iso2: 'LU', aliases: [], continent: 'Europe' },
  { name: 'Malta', iso2: 'MT', aliases: [], continent: 'Europe' },
  { name: 'Cyprus', iso2: 'CY', aliases: [], continent: 'Europe' },

  // Asia
  { name: 'China', iso2: 'CN', aliases: [], continent: 'Asia' },
  { name: 'India', iso2: 'IN', aliases: [], continent: 'Asia' },
  { name: 'Japan', iso2: 'JP', aliases: [], continent: 'Asia' },
  { name: 'Russia', iso2: 'RU', aliases: [], continent: 'Asia' },
  { name: 'Indonesia', iso2: 'ID', aliases: [], continent: 'Asia' },
  { name: 'Pakistan', iso2: 'PK', aliases: [], continent: 'Asia' },
  { name: 'Bangladesh', iso2: 'BD', aliases: [], continent: 'Asia' },
  { name: 'Philippines', iso2: 'PH', aliases: [], continent: 'Asia' },
  { name: 'Vietnam', iso2: 'VN', aliases: [], continent: 'Asia' },
  { name: 'Turkey', iso2: 'TR', aliases: [], continent: 'Asia' },
  { name: 'Iran', iso2: 'IR', aliases: [], continent: 'Asia' },
  { name: 'Thailand', iso2: 'TH', aliases: [], continent: 'Asia' },
  { name: 'South Korea', iso2: 'KR', aliases: [], continent: 'Asia' },
  { name: 'Saudi Arabia', iso2: 'SA', aliases: [], continent: 'Asia' },
  { name: 'Israel', iso2: 'IL', aliases: [], continent: 'Asia' },
  { name: 'United Arab Emirates', iso2: 'AE', aliases: ['UAE'], continent: 'Asia' },
  { name: 'Afghanistan', iso2: 'AF', aliases: [], continent: 'Asia' },
  { name: 'Iraq', iso2: 'IQ', aliases: [], continent: 'Asia' },
  { name: 'Kazakhstan', iso2: 'KZ', aliases: [], continent: 'Asia' },
  { name: 'Malaysia', iso2: 'MY', aliases: [], continent: 'Asia' },
  { name: 'Myanmar', iso2: 'MM', aliases: ['Burma'], continent: 'Asia' },
  { name: 'Nepal', iso2: 'NP', aliases: [], continent: 'Asia' },
  { name: 'North Korea', iso2: 'KP', aliases: [], continent: 'Asia' },
  { name: 'Oman', iso2: 'OM', aliases: [], continent: 'Asia' },
  { name: 'Qatar', iso2: 'QA', aliases: [], continent: 'Asia' },
  { name: 'Singapore', iso2: 'SG', aliases: [], continent: 'Asia' },
  { name: 'Sri Lanka', iso2: 'LK', aliases: [], continent: 'Asia' },
  { name: 'Syria', iso2: 'SY', aliases: [], continent: 'Asia' },
  { name: 'Taiwan', iso2: 'TW', aliases: [], continent: 'Asia' },
  { name: 'Uzbekistan', iso2: 'UZ', aliases: [], continent: 'Asia' },
  { name: 'Yemen', iso2: 'YE', aliases: [], continent: 'Asia' },

  // Africa
  { name: 'Nigeria', iso2: 'NG', aliases: [], continent: 'Africa' },
  { name: 'Egypt', iso2: 'EG', aliases: [], continent: 'Africa' },
  { name: 'South Africa', iso2: 'ZA', aliases: [], continent: 'Africa' },
  { name: 'Kenya', iso2: 'KE', aliases: [], continent: 'Africa' },
  { name: 'Ethiopia', iso2: 'ET', aliases: [], continent: 'Africa' },
  { name: 'DR Congo', iso2: 'CD', aliases: ['Democratic Republic of the Congo'], continent: 'Africa' },
  { name: 'Tanzania', iso2: 'TZ', aliases: [], continent: 'Africa' },
  { name: 'Algeria', iso2: 'DZ', aliases: [], continent: 'Africa' },
  { name: 'Morocco', iso2: 'MA', aliases: [], continent: 'Africa' },
  { name: 'Ghana', iso2: 'GH', aliases: [], continent: 'Africa' },
  { name: 'Ivory Coast', iso2: 'CI', aliases: ["Côte d'Ivoire"], continent: 'Africa' },
  { name: 'Madagascar', iso2: 'MG', aliases: [], continent: 'Africa' },
  { name: 'Angola', iso2: 'AO', aliases: [], continent: 'Africa' },
  { name: 'Cameroon', iso2: 'CM', aliases: [], continent: 'Africa' },
  { name: 'Libya', iso2: 'LY', aliases: [], continent: 'Africa' },
  { name: 'Mali', iso2: 'ML', aliases: [], continent: 'Africa' },
  { name: 'Mozambique', iso2: 'MZ', aliases: [], continent: 'Africa' },
  { name: 'Niger', iso2: 'NE', aliases: [], continent: 'Africa' },
  { name: 'Sudan', iso2: 'SD', aliases: [], continent: 'Africa' },
  { name: 'Uganda', iso2: 'UG', aliases: [], continent: 'Africa' },
  { name: 'Zambia', iso2: 'ZM', aliases: [], continent: 'Africa' },
  { name: 'Zimbabwe', iso2: 'ZW', aliases: [], continent: 'Africa' },
  
  // North America
  { name: 'United States', iso2: 'US', aliases: ['USA', 'America'], continent: 'North America' },
  { name: 'Canada', iso2: 'CA', aliases: [], continent: 'North America' },
  { name: 'Mexico', iso2: 'MX', aliases: [], continent: 'North America' },
  { name: 'Guatemala', iso2: 'GT', aliases: [], continent: 'North America' },
  { name: 'Cuba', iso2: 'CU', aliases: [], continent: 'North America' },
  { name: 'Haiti', iso2: 'HT', aliases: [], continent: 'North America' },
  { name: 'Dominican Republic', iso2: 'DO', aliases: [], continent: 'North America' },
  { name: 'Honduras', iso2: 'HN', aliases: [], continent: 'North America' },
  { name: 'Panama', iso2: 'PA', aliases: [], continent: 'North America' },
  { name: 'Costa Rica', iso2: 'CR', aliases: [], continent: 'North America' },
  { name: 'El Salvador', iso2: 'SV', aliases: [], continent: 'North America' },
  { name: 'Nicaragua', iso2: 'NI', aliases: [], continent: 'North America' },
  { name: 'Jamaica', iso2: 'JM', aliases: [], continent: 'North America' },
  { name: 'Trinidad and Tobago', iso2: 'TT', aliases: [], continent: 'North America' },

  // South America
  { name: 'Brazil', iso2: 'BR', aliases: [], continent: 'South America' },
  { name: 'Argentina', iso2: 'AR', aliases: [], continent: 'South America' },
  { name: 'Colombia', iso2: 'CO', aliases: [], continent: 'South America' },
  { name: 'Peru', iso2: 'PE', aliases: [], continent: 'South America' },
  { name: 'Venezuela', iso2: 'VE', aliases: [], continent: 'South America' },
  { name: 'Chile', iso2: 'CL', aliases: [], continent: 'South America' },
  { name: 'Ecuador', iso2: 'EC', aliases: [], continent: 'South America' },
  { name: 'Bolivia', iso2: 'BO', aliases: [], continent: 'South America' },
  { name: 'Paraguay', iso2: 'PY', aliases: [], continent: 'South America' },
  { name: 'Uruguay', iso2: 'UY', aliases: [], continent: 'South America' },
  { name: 'Guyana', iso2: 'GY', aliases: [], continent: 'South America' },
  { name: 'Suriname', iso2: 'SR', aliases: [], continent: 'South America' },
  
  // Oceania
  { name: 'Australia', iso2: 'AU', aliases: [], continent: 'Oceania' },
  { name: 'New Zealand', iso2: 'NZ', aliases: [], continent: 'Oceania' },
  { name: 'Papua New Guinea', iso2: 'PG', aliases: [], continent: 'Oceania' },
  { name: 'Fiji', iso2: 'FJ', aliases: [], continent: 'Oceania' },
  { name: 'Solomon Islands', iso2: 'SB', aliases: [], continent: 'Oceania' },
  { name: 'Vanuatu', iso2: 'VU', aliases: [], continent: 'Oceania' },
  
  // Antarctica
  { name: 'Antarctica', iso2: 'AQ', aliases: [], continent: 'Antarctica' },
];
